{
 "title": "Simulated Speed",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Driver Speeds Today",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN \"top_speed\" BETWEEN 0 AND 20 THEN '0-20'\r\n    WHEN \"top_speed\" BETWEEN 21 AND 30 THEN '20-30'\r\n    WHEN \"top_speed\" BETWEEN 31 AND 50 THEN '30-50'\r\n    ELSE '51+'\r\n  END AS \"range\",\r\n  COUNT(*) \r\nFROM simulate_speed \r\nWHERE DATE(time) = DATE(NOW()) \r\nGROUP BY \"range\";"
    }
   ]
  },
  {
   "title": "Driver Speeds This Morning",
   "type": "bargauge",
   "description": "05 - 09",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN \"top_speed\" BETWEEN 0 AND 20 THEN '0-20'\r\n    WHEN \"top_speed\" BETWEEN 21 AND 30 THEN '20-30'\r\n    WHEN \"top_speed\" BETWEEN 31 AND 50 THEN '30-50'\r\n    ELSE '51+'\r\n  END AS \"range\",\r\n  COUNT(*) \r\nFROM simulate_speed \r\nWHERE DATE(time) = DATE(NOW()) AND EXTRACT(HOUR FROM time) >= 5 AND EXTRACT(HOUR FROM  time) < 9\r\nGROUP BY \"range\";"
    }
   ]
  },
  {
   "title": "Simulated Speed",
   "type": "timeseries",
   "description": "Simulated speed values to preview dashboard for actual values.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM simulate_speed \r\nORDER BY time DESC\r\nLIMIT 5000;"
    }
   ]
  },
  {
   "title": "Simulated Speed",
   "type": "timeseries",
   "description": "Simulated speed values to preview dashboard for actual values.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM simulate_speed \r\nORDER BY time DESC\r\nLIMIT 5000;"
    }
   ]
  },
  {
   "title": "Driver Speeds This Morning",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN \"top_speed\" BETWEEN 0 AND 20 THEN '0-20'\r\n    WHEN \"top_speed\" BETWEEN 21 AND 30 THEN '20-30'\r\n    WHEN \"top_speed\" BETWEEN 31 AND 50 THEN '30-50'\r\n    ELSE '51+'\r\n  END AS \"range\",\r\n  COUNT(*) \r\nFROM simulate_speed \r\nWHERE DATE(time) = DATE(NOW()) AND EXTRACT(HOUR FROM time) >= 5 AND EXTRACT(HOUR FROM time) < 9\r\nGROUP BY \"range\";"
    }
   ]
  },
  {
   "title": "Driver Speeds Today",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN \"top_speed\" BETWEEN 0 AND 20 THEN '0-20'\r\n    WHEN \"top_speed\" BETWEEN 21 AND 30 THEN '20-30'\r\n    WHEN \"top_speed\" BETWEEN 31 AND 50 THEN '30-50'\r\n    ELSE '51+'\r\n  END AS \"range\",\r\n  COUNT(*) \r\nFROM simulate_speed \r\nWHERE DATE(time) = DATE(NOW()) \r\nGROUP BY \"range\";"
    }
   ]
  },
  {
   "title": "Driver Speeds Today",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  CASE \r\n    WHEN \"top_speed\" BETWEEN 0 AND 20 THEN '0-20'\r\n    WHEN \"top_speed\" BETWEEN 21 AND 30 THEN '20-30'\r\n    WHEN \"top_speed\" BETWEEN 31 AND 50 THEN '30-50'\r\n    ELSE '51+'\r\n  END AS \"range\",\r\n  COUNT(*) \r\nFROM simulate_speed \r\nWHERE DATE(time) = DATE(NOW()) \r\nGROUP BY \"range\";"
    }
   ]
  }
 ]
}